### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by wzz893434299** [ucas-vg/P2BNet#13]
Hello,I would like to know why the memory has been increasing when training?The device are 4* RTX3090.Is there a solution to solve the problem? Thank you.

**Comment by Darren-pfchen** [comment]
can u provide the environmental version

**Comment by gjgj45** [comment]
Hi! I have the same problem.  My device is 4*A100(40G), torch 1.13, torchvision 0.14, mmcv-full 1.7.0

**Comment by Darren-pfchen** [comment]
你好，根据我以往的经验，是由于pytorch和mmcv的版本不一致导致的，我还没有尝试过在新的pytorch和mmcv上调试我的代码。你可以恢复到我github的环境版本（pytorch=1.9.0，mmcv-full=1.4 (cuda11.1，不过应该不影响)，另外如果你在新的环境上找到bug欢迎你告诉我修改（我预估是某个函数版本更新导致的内存泄露）。

**Comment by gjgj45** [comment]
> 你好，根据我以往的经验，是由于pytorch和mmcv的版本不一致导致的，我还没有尝试过在新的pytorch和mmcv上调试我的代码。你可以恢复到我github的环境版本（pytorch=1.9.0，mmcv-full=1.4 (cuda11.1，不过应该不影响)，另外如果你在新的环境上找到bug欢迎你告诉我修改（我预估是某个函数版本更新导致的内存泄露）。

我后来定位到我的问题是因为cuda driver版本过高（12.1），降低cuda driver到11.4后解决了问题。

**Comment by Darren-pfchen** [comment]
> 

对于漏标的问题，现有的P2BNet是不能解决的，对于距离物体中心距离比较大的，由于P2BNet是根据点周围采样，所以我建议这几个策略：1）在CBP sampling的增加长宽比的多样性，尺度那个也能调，2）在CBP时候就加入上下左右抖动（可能这个还蛮重要的，因为P2BNet有效的前提是，你采样的框至少有一个能cover住整个目标，你可以可视化这个采样框看看），3）在PBR时候，抖动幅度增加，并且长宽比那个你也能调。上面那些调得怎么样，在训练log的meanIoU就能看出来，一般训个1轮甚至半轮就能看出来，不用全部训。另外，这个问题也是值得研究的，怎么样在“物体中心距离比较大”的情况下，也能预测出很好的框。

**Comment by Darren-pfchen** [comment]
> > 你好，根据我以往的经验，是由于pytorch和mmcv的版本不一致导致的，我还没有尝试过在新的pytorch和mmcv上调试我的代码。你可以恢复到我github的环境版本（pytorch=1.9.0，mmcv-full=1.4 (cuda11.1，不过应该不影响)，另外如果你在新的环境上找到bug欢迎你告诉我修改（我预估是某个函数版本更新导致的内存泄露）。
> 
> 我后来定位到我的问题是因为cuda driver版本过高（12.1），降低cuda driver到11.4后解决了问题。

对于漏标的问题，现有的P2BNet是不能解决的，对于距离物体中心距离比较大的，由于P2BNet是根据点周围采样，所以我建议这几个策略：1）在CBP sampling的增加长宽比的多样性，尺度那个也能调，2）在CBP时候就加入上下左右抖动（可能这个还蛮重要的，因为P2BNet有效的前提是，你采样的框至少有一个能cover住整个目标，你可以可视化这个采样框看看），3）在PBR时候，抖动幅度增加，并且长宽比那个你也能调。上面那些调得怎么样，在训练log的meanIoU就能看出来，一般训个1轮甚至半轮就能看出来，不用全部训。另外，这个问题也是值得研究的，怎么样在“物体中心距离比较大”的情况下，也能预测出很好的框。

**Comment by ZiMo-Chen** [comment]
> > 你好，根据我以往的经验，是由于pytorch和mmcv的版本不一致导致的，我还没有尝试过在新的pytorch和mmcv上调试我的代码。你可以恢复到我github的环境版本（pytorch=1.9.0，mmcv-full=1.4 (cuda11.1，不过应该不影响)，另外如果你在新的环境上找到bug欢迎你告诉我修改（我预估是某个函数版本更新导致的内存泄露）。
> 
> 我后来定位到我的问题是因为cuda driver版本过高（12.1），降低cuda driver到11.4后解决了问题。

你好， 你是怎么定位到问题的，我尝试了几个pytorch高版本的（>=1.10) 都会出现显存一直上涨的问题，我也尝试降低 cuda driver为11.4还是出现问题了。我想用高版本的pytorch 训练效率更高些

**Comment by Luo-Z13** [comment]
> 你好，根据我以往的经验，是由于pytorch和mmcv的版本不一致导致的，我还没有尝试过在新的pytorch和mmcv上调试我的代码。你可以恢复到我github的环境版本（pytorch=1.9.0，mmcv-full=1.4 (cuda11.1，不过应该不影响)，另外如果你在新的环境上找到bug欢迎你告诉我修改（我预估是某个函数版本更新导致的内存泄露）。

你好，我的环境如下：pytorch=1.8.0，mmcv-full=1.4，仍然出现显存持续上涨问题，我推测是否是因为refine stage的过程中有某个函数出现了问题？目前我还没有定位到具体问题。

Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA TITAN RTX
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.8.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.13.0+c820f32

**Comment by Luo-Z13** [comment]
@Darren-pfchen
